language: node_js
sudo: required
cache:
  directories:
    - node_modules
node_js:
    - "6"
env:
  - COVERALLS=1
git:
  depth: 10
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - 'npm config set loglevel error'
  - docker-compose up -d
before_script:
  - sleep 10
  - docker ps -a
  - docker logs chassis_adb
  - docker logs chassis_zk
  - docker logs chassis_kafka
scripts:
  - 'npm test'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
