language: node_js
sudo: required
node_js:
    - "6"
env:
  - COVERALLS=1
git:
  depth: 10
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - 'npm config set loglevel error'
  - docker network create --driver bridge chassis_net
  - docker run --name chassis_zk -d --net=chassis_net -p 2181:2181 wurstmeister/zookeeper:3.4.6
  - docker run --name chassis_kafka -d --net=chassis_net -p 9092:9092 -e KAFKA_ADVERTISED_HOST_NAME=127.0.0.1 -e KAFKA_ZOOKEEPER_CONNECT=zk:2181 -v /var/run/docker.sock:/var/run/docker.sock --link chassis_zk:zk wurstmeister/kafka:0.9.0.1
  - sudo mkdir -p /sync1/invcontainervolumes/
  - sudo chmod -R 777 /sync1/invcontainervolumes/
  - docker run --name chassis_adb -d -p 127.0.0.1:8529:8529 -v /sync1/invcontainervolumes/chassis_adb:/var/lib/arangodb -e ARANGO_NO_AUTH=1 arangodb:2.8.9
before_script:
  - wget http://apache.mirror.iphh.net/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz
  - tar -zxvf kafka_2.11-0.9.0.1.tgz
  - ./kafka_2.11-0.9.0.1/bin/kafka-topics.sh --create --zookeeper 127.0.0.1:2181 --replication-factor 1 --partitions 1 --topic test
  - sleep 10
  - docker ps -a
  - docker logs chassis_adb
  - docker logs chassis_zk
  - docker logs chassis_kafka
scripts:
  - 'npm test'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
